### PR TITLE
Set some default retries for url.yml in the install task

### PR DESCRIPTION
**Pull request by jajik**
It occurs pretty regularly (at least in my fork) that one of the downloads fails. This PR adds a few retries so that some random glitches are eliminated.

### CODE REVIEW

**Comment by jajik** [comment]
Also, is there any reason for running CI only on `main` branches for pushes? It seems rather inconvenient for the development..

**Comment by rpelisse** [comment]
Thanks, it's something I've been toying around in my head for while... LGTM, @guidograzioli any concerns?

**Comment by rpelisse** [comment]
@jajik If you would not mind updating your PR to replace the hard coded value by variable defined in the roles' defaults, that would be great :) Depending on env, I expect users to want to tweak these settings.

**Comment by jajik** [comment]
@rpelisse I'm afraid it's getting a little bit overengineered, but check out the latest changes.

**Comment by rpelisse** [comment]
@jajik Oh sorry, that was maybe misleading. I did not meant adding Envvars, just variable in the defaults values of the role:
```
roles/jws/defaults.yml
...
jws_url_download_timeout: 
jws_url_download_retries: 
```

**Comment by jajik** [comment]
@rpelisse Check it out now.

**Comment by rpelisse** [comment]
That's great! And thanks you for adding the documentation, we often forget to do that.

Can I ask you for two more changes?

1) We also need to document this new defaults in the meta/arguments_specs.yml file
2) Can you remove the extra whitespaces added in roles/jws/README.md?

After that, I think we should be good to go (or rather good to rebase & merge)!

**Comment by jajik** [comment]
>     2. Can you remove the extra whitespaces added in roles/jws/README.md?

Which spaces do you mean? Feel free to mark them directly through a review. I tried to preserve the "nice" table structure.

**Comment by guidograzioli** [comment]
These two:
jws_url_download_timeout: 
jws_url_download_retries: 

need to be defined in meta/argument_specs.yml too

**Comment by jajik** [comment]
> These two: jws_url_download_timeout: jws_url_download_retries:
> 
> need to be defined in meta/argument_specs.yml too

Yes, @rpelisse mentioned it yesterday. I'll do that as soon as he'll get back wrt the whitespaces so that it's done at once. :slightly_smiling_face:

**Comment by jajik** [comment]
> > ```
> > 2. Can you remove the extra whitespaces added in roles/jws/README.md?
> > ```
> 
> Which spaces do you mean? Feel free to mark them directly through a review. I tried to preserve the "nice" table structure.

@rpelisse ^^

**Comment by rpelisse** [comment]
@jajik Oh sorry, I thought it was clear! I just looked at the tabs "changes" of the PR and there you can see a lot of whitespaces have been added to the table:
whitespaces

**Comment by jajik** [comment]
> @jajik Oh sorry, I thought it was clear! I just looked at the tabs "changes" of the PR and there you can see a lot of whitespaces have been added to the table: whitespaces

Yes, that's because the new variables are wider than the column, so in order to keep it aligned the same way it is now, it is necessary to add a few more.

If you don't want to have the columns aligned any longer, should I remove the extra spaces already in as well?

**Comment by rpelisse** [comment]
Then, I would just separate this changes into a one commit with the comment "whitespaces", if you don't mind.

**Comment by jajik** [comment]
> Then, I would just separate this changes into a one commit with the comment "whitespaces", if you don't mind.

so you want to preserve the formatting, but in a different commit?

**Comment by rpelisse** [comment]
Yes, exactly - sorry if it was not clear. The rational is that this way we'll get a cleaner commit for the actual change, but also (even if it does not apply here), doing formatting in a separate commit is helping down the road if we use git bisect, for instance, to determine, which commit introduced a regression.

(Once, I was able to id like that the faulty commit, but it was littered by whitespaces changes that made it difficult to figure out what actual change could be the issue... I've learned my lesson ;) )

**Comment by jajik** [comment]
Ok, everything should be in place now.

**Pull request merged**
